### ISSUE TITLE
Crash on the first analysis

### ISSUE THREAD

**Issue by pcav** [LCacheux68224/ProportionalCircles#1]
The plugin fails.

Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "/home/paolo/Desktop/butta/qgis_test/python/plugins/ProportionalCircles/proportionalcircles.py", line 155, in run
    analysisArea = self.layerArea(analysisLayer)
  File "/home/paolo/Desktop/butta/qgis_test/python/plugins/ProportionalCircles/proportionalcircles.py", line 447, in layerArea
    if areaOfAnalysis.selectedFeatures():
AttributeError: 'NoneType' object has no attribute 'selectedFeatures'

**Comment by LCacheux68224** [comment]
Ok. Apparently, it fails because the plugin needs a polygon layer that covers the all analysis area to calculate the automatic scale. I will do some correction in a few days.
